name: Check setup

runs:
  using: composite
  steps:
    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Get Bun cache directory
      shell: bash
      run: |
        echo "STORE_PATH=${HOME}/.bun/install/cache" >> $GITHUB_ENV

    - name: Setup Bun cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      run: bun install

    - name: Create environment variables file
      shell: bash
      run: |
        cat << EOF > .env.local
        SLACK_APP_TOKEN="xapp-your-app-token"
        SLACK_BOT_TOKEN="xoxb-your-bot-token"
        SLACK_SIGNING_SECRET="your-signing-secret"
        SLACK_SOCKET_MODE=true
        PORT=3000
        REDIS_URL="redis://localhost:6379"
        HACKCLUB_API_KEY="sk-hc-your-hackclub-api-key"
        OPENROUTER_API_KEY="sk-or-your-openrouter-api-key"
        LOG_DIRECTORY="logs"
        LOG_LEVEL="info"
        EXA_API_KEY=""
        VERCEL_TOKEN="your-vercel-oidc-token"
        VERCEL_PROJECT_ID="prj_abc"
        EOF
