import { defineConfig } from "@cspell/cspell-types";

export default defineConfig({
  version: "0.2",
  language: "en",
  import: ["@cspell/dict-bash/cspell-ext.json"],
  ignorePaths: [
    "**/.cache/**",
    "**/.git/**",
    "**/.turbo/**",
    "**/dist/**",
    "**/node_modules/**",
    "**/bun.lock",
    "**/bun.lockb",
  ],
  ignoreRegExpList: [
    "/https?:\\/\\/\\S+/g",
    "/apiKey='[a-zA-Z0-9-]{32}'/g",
    "/0x[a-fA-F0-9]+/g",
  ],
  words: [
    "Anirudh",
    "Devarsh",
    "Sriram",
    "agentmail",
    "AGENTMAIL",
    "automations",
    "behaviour",
    "cynicist",
    "daytonaio",
    "Daytona",
    "dbgenerate",
    "docstrings",
    "exalabs",
    "exfiltration",
    "fdfind",
    "gork",
    "GORK",
    "gorkie",
    "Gork's",
    "hackclub",
    "HACKCLUB",
    "healthcheck",
    "homelab",
    "hostnames",
    "imgork",
    "isready",
    "jsonrepair",
    "Jsonify",
    "lefthook",
    "livecrawl",
    "mariozechner",
    "matplotlib",
    "modelcontextprotocol",
    "moltbook",
    "mpim",
    "neondatabase",
    "networkidle",
    "numpy",
    "ONLCR",
    "openrouter",
    "OPENROUTER",
    "poppler",
    "Qwik",
    "roleplay",
    "shitposter",
    "stty",
    "summarisation",
    "summarise",
    "Summarise",
    "summarised",
    "summariser",
    "Summarising",
    "tesseract",
    "thonk",
    "typebox",
    "Turborepo",
    "ultracite",
    "Ultracite",
    "webdev",
    "xapp",
    "xoxb",
    "zadd",
    "zcard",
    "zrangebyscore",
    "zrem",
    "zremrangebyscore",
  ],
});
